### ISSUE TITLE
Associations throw an error

### ISSUE THREAD

**Issue by demeshik** [BlinkUX/sequelize-mock#10]
When I try to specify an associations, for example belongsTo or hasOne, I get an error:
"Can not set property "getUser" of undefined"
And a pointer to the "model.js" file: 560: 37

**Comment by ktsashes** [comment]
Ah, yeah, I see the issue. Missed a spot for some of the rewrites. That's a bad one. I'll get a fix out ASAP. Thanks for the catch and for reporting it.

**Comment by ktsashes** [comment]
Should be fixed in v0.8.1. Upgrading should allow you to create associations as expect.
