### ISSUE TITLE
FindAndCount and FindAndCountAll

### ISSUE THREAD

**Issue by Lampei** [BlinkUX/sequelize-mock#13]
I'm currently working with some methods that do not appear to be mocked onto the model - findAndCount/findAndCountAll.  I tried adding them via the instanceMethods when defining the mock, but that did not appear to work for me either.  Don't know if that's a separate issue (or something I'm doing wrong) but kept getting undefined when trying to call the created method.

**Comment by ktsashes** [comment]
Yeah, those functions aren't mocked out yet. Should be a lot easier with the `QueryInterface` in place, they just slipped past me. I'll take a look.

As for the `instanceMethods` option, that will add it to instances of the model, but not to the model itself. To add it to the defined model, you should be able to just do `myModel.findAndCount = function () { /* ... */ }`.

**Comment by TerryMooreII** [comment]
I am also in need of this

**Comment by TerryMooreII** [comment]
Added PR #32 which adds FindAndCountAll.

**Comment by ktsashes** [comment]
Thanks again @TerryMooreII for your work on this. The PR has been merged and will go out with the next release to add support for this.

**Comment by ktsashes** [comment]
This change has gone out and is available in v0.10.0.
