### ISSUE TITLE
Typings for TypeScript?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [BlinkUX/sequelize-mock#15]
Is there any interest in making typings for this project available for TypeScript?

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by ktsashes** [comment]
Does Sequelize have an equivalent file? Just trying to figure out if this is for parity with Sequelize or for functionality on it's own?

**Comment by JoshuaKGoldberg** [comment]
Sequelize does have its own typings: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize / https://www.npmjs.com/package/@types/sequelize. 

The use case here is that I have a project built with TypeScript that uses Sequelize and the Sequelize typings. I'd like to investigate using sequelize-mock for tests, but don't get happy build-time verification for it because there are no provided typings.

**Comment by ktsashes** [comment]
Awesome. I'll take a look as I get a chance. I haven't done much TS coding but this looks like it would be a relatively straight-forward thing to tackle. Especially since many of the declarations should (hopefully) match with Sequelize.

**Comment by d-luk** [comment]
Any update on this?

**Comment by JoshuaKGoldberg** [comment]
Oh wow I forgot about this thread! FWIW I've since turned to the opinion espoused by the TypeScript team that libraries not written in TypeScript often are better off putting types in DefinitelyTyped. So I'll close this issue.

**Comment by ctapisab** [comment]
@JoshuaKGoldberg I didn't find sequelize-mock in DefinitelyTyped. Is there any other way to use have the Typescript definitions of sequelize-mock?

**Comment by JoshuaKGoldberg** [comment]
I wouldn't know; I haven't used this library in years. 😉 

A guess: you'll have to contribute them to DefinitelyTyped yourself.
