### ISSUE TITLE
Docs glitch?   require('sequelize-mock')();

### ISSUE THREAD

**Issue by martinhbramwell** [BlinkUX/sequelize-mock#26]
Your[ GitHub README getting started instructions](https://github.com/BlinkUX/sequelize-mock) state ...

##### Start by importing the library

     var SequelizeMock = require('sequelize-mock');

##### Initialize the library as you would Sequelize

     var DBConnectionMock = new SequelizeMock();

-----
... but your [ReadTheDocs instructions](https://sequelize-mock.readthedocs.io/en/stable/docs/getting-started/) state ...

#### Make Fake DB Connection

Because Sequelize Mock is meant ...  .... any actual connection data.

     var SequelizeMock = require('sequelize-mock')();
     var dbMock = new SequelizeMock();

-----
If I follow the second version's `require`, with its trailing function parenthesis, I get the error:

    TypeError: Cannot set property 'queryInterface' of undefined

**Comment by ktsashes** [comment]
Thanks for letting me know about this issue! The correct code should be (as it looks like you noticed):

```javascript
var SequelizeMock = require('sequelize-mock');
var dbMock = new SequelizeMock();
```

Looks like I accidentally had the extra `()` left over from a different version of that example code. I've fixed it and it should go out with our next release.

**Comment by alanhr** [comment]
Hi @ktsashes , you need fix this problem in doc. :)
