### ISSUE TITLE
Clarification on this repo

### ISSUE THREAD

**Issue by AnthonyTsang** [BlinkUX/sequelize-mock#28]
```javascript
UserMock.findOne({
	where: {
		username: 'my-user',
	},
}).then(function (user) {
	// `user` is a Sequelize Model-like object
	user.get('id');         // Auto-Incrementing ID available on all Models
	user.get('email');      // 'email@example.com'; Pulled from default values
	user.get('username');   // 'my-user'; Pulled from the `where` in the query
	
	user.myTestFunc();      // Will return 'Test User' as defined above
});
```

In this example, `findOne()` always return something which basically a combination of where clause and default value. It means it will never going to actually look for an instance from some storage. This behaviour does not match what I expected a mock should be. Mock by my understanding is an object which behave like the original object, but easy to be control its behaviours. Specific for sequelize, the use case what my immediate understanding is to have all behaviours a sequelize has without hitting a real database. Which I dunno how to achieve with this repo. How do I attempt to have and have not result from `findOne()`?

**Comment by ktsashes** [comment]
The project is specifically meant to be full control over the returned data without hitting a DB.

The example there is showing off the `autoQueryFallback` functionality to make some testing easier by default. This is turned on by default but can be disabled at either the `SequelizeMock` or the `ModelMock` levels. The goal of it is to get basic tests up and running quickly to increase test coverage, while allowing full control as needed for more detailed testing.

For returning data, we have 4 ways to control the data:

 1. `$useHandler` defines a function that will be called where you can return data for a query
 2. `$queueResult` and `$queueFailure` can be used to queue results to be returned in a specific order
 3. The automated fallback can be used to do basic tests (again, can be turned off)
 4. Define a generic fallback method and pass it in with the query itself (though this has limited use cases)

For more information, I'd recommend checking out our [Mock Queries](https://sequelize-mock.readthedocs.io/en/stable/docs/mock-queries/) documentation page where it goes over each of these in more detail.
