### ISSUE TITLE
TypeError: Utils.stack(...).getFileName is not a function

### ISSUE THREAD

**Issue by KMNowak** [BlinkUX/sequelize-mock#35]
Hello everyone!

I started using your library, because seems to be extremely useful in my project. Unfortunately, while running `jest` test, an error occurs:

```
TypeError: Utils.stack(...).getFileName is not a function
at Sequelize.Object.<anonymous>.Sequelize.import (node_modules/sequelize-mock/src/sequelize.js:332:44)
```
It points to line:
https://github.com/BlinkUX/sequelize-mock/blob/edac5af69d5363d3a84b62bff2366a1c9fa316d5/src/sequelize.js#L332

Reference to original `sequelize` models  looks like:
```js
this.DB.import(`./{modelName}`)
```
All import paths were overriden by `$overrideImport` method in many ways, but none succeeded.

What could be the reason of that behaviour? 

Thank you in advance for any response.

**Comment by ktsashes** [comment]
Should be fixed in v0.10.1. Try updating and let me know if you still have issues

**Comment by KMNowak** [comment]
I really appreciate such quick help!
It fixed pervious case, but another one occured:

When exporting models by 
```js
export default (DB:Sequelize, Datatypes: Datatypes) => sequelizeMock.define(...)
```
line:
```
this.importCache[importPath] = require(importPath).default(this, DataTypes);
```
in place of 
https://github.com/BlinkUX/sequelize-mock/blob/fe656c6aea363dff80dc108cfbaa054c0dcf9364/src/sequelize.js#L338
fixes issue 
```
require(...) is not a function`
```

I hope you will find it helpful.

**Comment by ktsashes** [comment]
Ah I missed support for `export default` in their code base. I will try to add support for that when I get a chance. I've added a separate bug for that as issue #36
