### ISSUE TITLE
DataTypes not being returned

### ISSUE THREAD

**Issue by fnawratil** [BlinkUX/sequelize-mock#37]
In sequelize.js "data-types" is required, called with an empty object and then assigned to DataTypes. The function being called does however not return anything and DataTypes remains undefined.

This in turn renders "import" unusable as it passes the model undefined instead of the DataTypes

**Comment by ktsashes** [comment]
Did you get this figured out?

**Comment by raamSoftwire** [comment]
It looks like you've fixed this now, when will you release an update?

**Comment by ktsashes** [comment]
Sorry, didn't realize what this was referring to. This has been fixed and released in v0.10.2

**Comment by raamSoftwire** [comment]
Great, thank you.
