### ISSUE TITLE
Object Association Persistence?

### ISSUE THREAD

**Issue by tills13** [BlinkUX/sequelize-mock#38]
I have a flow that looks like

```
return Party.create().then((party) => {
  return PartyBudget.create({ 
    type: input.budgetType || BUDGET_UNLIMITED 
  }).then(pb => {
    return party.setBudget(pb)
  })
})
```

in my tests, I am making sure that providing no input to the above produces a `Party` with a `PartyBudget` with an unlimited budget.

```
return graphql(schema, query, {}, state).then((result) => {
  assert.equal(result.party.budget.type, BUDGET_UNLIMITED) // this doesn't work (type is null/undefined)

  return Party.findById(result.party.id).then((party) => {
    return party.getBudget().then((budget) => {
      assert.equal(budget.type, BUDGET_UNLIMITED) // this doesn't work (type is null/undefined)
    })
  })
})
```

For _reasons_ (mostly obfuscation), the default value isn't set at the model level.

It seems that `sequelize-mock` creates a new instance instead of returning the associated object (in fact, `setBudget` is a noop).

Am I SOL on this (i.e. beyond the scope of `sequelize-mock`?)

**Comment by tills13** [comment]
the first `assert` is checking the result of the `create`
the second `assert` is checking the "saved" value

it's more of an integration test, which I guess is a little out of scope for this project.

**Comment by ktsashes** [comment]
Integration tests are entirely possible with this mocking framework, however storing/retrieving results is not. The library is meant for mocking out the data for tests and returning controlled values. We do not store or retrieve data in any way.

If you want tests to run with an "mock" DB behind it so you can run tests that insert and then retrieve data, we recommend using native Sequelize with an in-memory SQLite DB. That will allow you to use Sequelize as you normally would and test data retrieval from an actual DB while also not polluting your real DBs. This is also the way the Sequelize team has recommended doing this sort of testing in the past.
