### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by josephwegner** [BlinkUX/sequelize-mock#78]
Hi friends!

I’ve been using sequeilize-mock in one of my projects and have been quite enjoying it. That said, there are some enhancements I would love to see. I also see there are similar feelings from the community here, but unfortunately this project seems abandoned. 

I would like to try to revive this project, either as taking over maintenance entirely or joining the existing team of maintainers.

Is this a situation that y’all would be open to? Or are there other ways I can help breathe some life back into this project?

**Comment by LoveAndCoding** [comment]
As the original maintainer of this repo, I'll provide a little context and info here.

I no longer have write access to this repository. This was created based on an internal need for a long-term project I was working on at @BlinkUX. But I left more than a year ago now and when I did, I tried to pass on ownership of this repo, but they had not hired a replacement before I left so it is likely information and context here was lost.

That said, this was originally written against sequelize v3 before v4 or v5 came out and as such is wildly out of date. Also, as much as I would like to say this is a solid foundation, I don't believe it is anymore. The rewrite between v3 and v4 of sequelize was significant under the hood, which required quite a bit of work based on how this mocking worked (Model/Instance code being the biggest effort, the last time I checked). And I haven't used sequelize in a while, but I imagine v5 may have been a similar large block of changes.

If @BlinkUX were willing to pass on maintainership to someone else, it'll likely be a fairly sizeable undertaking to convert this all the way up to v5 support. There are a few tedious tasks that I think could be saved from having to redo with using this as a base, but this code was written in a different era.

Either way, I likely don't have time to do much contributions to coding to help get this up to par, but in whatever the path forward is, I'm happy to provide whatever context and information I can to help this project succeed.
