### ISSUE TITLE
How to handle array of model data

### ISSUE THREAD

**Issue by zachariahtimothy** [BlinkUX/sequelize-mock#9]
Hey there, love the simplicity and approach of this lib, thank you for writing it. 

I just set it up and it works great within a minute or two, but I am confused about how I can mock an array of data (model.findAll) using this technique. Trying to keep my tests simple, but I do need to verify my report is querying a returning filtered arrays as expected. 

Thanks again!

**Comment by ktsashes** [comment]
Glad you are finding it useful.

I've just released v0.8.0 today which should hopefully help address that. We now support the ability to specify what should be returned by a (non-)query to the "Mock DB".

If you upgrade to v0.8.0, you can simply use `model.$queueResult`, and pass in an array of the values you'd like to test. Then, when your code next tries to hit the non-existent DB, it will return your array to the promise.

We still support our automatic query result generation as a fallback, but you can now turn that off if you prefer more control over your tests.

The full documentation for the new feature can be found under [Mock Queries](https://sequelize-mock.readthedocs.io/en/stable/docs/mock-queries/) in our documentation

Hope that helps
